# yamllint configuration for GitHub Actions workflows
# See: https://yamllint.readthedocs.io/

extends: default

rules:
  # Line length - GitHub Actions can have long lines
  line-length:
    max: 150
    level: warning

  # Comments
  comments:
    min-spaces-from-content: 2

  # Indentation - GitHub Actions uses 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true

  # Allow truthy values (on, off, yes, no)
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']

  # Document start (---) not required for GitHub Actions
  document-start: disable

  # Allow empty values
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  .github/workflows/test_lint.yml
