# Example CI Workflow
# Copy this to your project's .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:
    branches:
      - main
      - 'release-*'

jobs:
  build:
    name: Build and Test
    uses: artagon/artagon-common/.github/workflows/maven_build.yml@main
    with:
      java-version: '25'
      run-tests: true
      run-integration-tests: false

  security-scan:
    name: Security Scan
    needs: build
    uses: artagon/artagon-common/.github/workflows/maven_security_scan.yml@main
    with:
      run-dependency-check: true
      run-ossindex-audit: true
      run-trivy-scan: true
      fail-on-severity: 'HIGH'
