# Example: Release Branch Validation Workflow
#
# This workflow validates release branches and optionally deploys to staging.
# Copy this to your project's .github/workflows/release-branch.yml
#
# Purpose: Validate release branch before triggering actual release.
#
# For complete Java/Maven release strategy, see:
# https://github.com/artagon/artagon-workflows/blob/main/docs/RELEASE_JAVA.md

name: Release Branch Validation

on:
  push:
    branches:
      - 'release-*'
  workflow_dispatch:
    inputs:
      deploy-to-staging:
        description: 'Deploy artifacts to staging after validation'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  validate-release-branch:
    name: Validate Release Branch
    uses: artagon/artagon-workflows/.github/workflows/maven_release_branch.yml@v1
    with:
      java-version: '21'  # Or 17, 25
      deploy-to-staging: ${{ inputs.deploy-to-staging || false }}
    secrets: inherit
