# Example Release Workflow
# Copy this to your project's .github/workflows/release.yml

name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
      next-snapshot-version:
        description: 'Next snapshot version (leave empty for auto-increment)'
        required: false
        type: string
      auto-release-nexus:
        description: 'Automatically release from Nexus staging'
        required: false
        type: boolean
        default: false

jobs:
  release:
    name: Release to Maven Central
    if: startsWith(github.ref, 'refs/heads/release-')
    uses: artagon/artagon-common/.github/workflows/maven_release.yml@main
    with:
      java-version: '25'
      release-version: ${{ github.event.inputs.release-version }}
      next-snapshot-version: ${{ github.event.inputs.next-snapshot-version }}
      deploy-profile: 'ossrh-deploy,artagon-oss-release'
      auto-release-nexus: ${{ github.event.inputs.auto-release-nexus }}
      create-github-release: true
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
