# Example Snapshot Deployment Workflow
# Copy this to your project's .github/workflows/snapshot-deploy.yml

name: Deploy Snapshot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-snapshot:
    name: Deploy Snapshot to OSSRH
    if: github.ref == 'refs/heads/main'
    uses: artagon/artagon-common/.github/workflows/maven_deploy.yml@main
    with:
      java-version: '25'
      deploy-profile: 'ossrh-deploy,artagon-oss-release'
      skip-tests: true
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
