name: Test Bazel CI Workflow

on:
  pull_request:
    paths:
      - '.github/workflows/bazel_multi_ci.yml'
      - '.github/workflows/test_bazel_ci.yml'
      - 'test/fixtures/bazel/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/bazel_multi_ci.yml'
      - '.github/workflows/test_bazel_ci.yml'
      - 'test/fixtures/bazel/**'
  workflow_dispatch:

jobs:
  test-minimal:
    name: Test Minimal Configuration
    uses: ./.github/workflows/bazel_multi_ci.yml
    with:
      working-directory: test/fixtures/bazel
    permissions:
      contents: read

  test-release-config:
    name: Test Release Configuration
    uses: ./.github/workflows/bazel_multi_ci.yml
    with:
      bazel-configs: 'release'
      working-directory: test/fixtures/bazel
    permissions:
      contents: read

  test-debug-config:
    name: Test Debug Configuration
    uses: ./.github/workflows/bazel_multi_ci.yml
    with:
      bazel-configs: 'debug'
      working-directory: test/fixtures/bazel
    permissions:
      contents: read

  verify:
    name: Verify Test Results
    needs: [test-minimal, test-release-config, test-debug-config]
    runs-on: ubuntu-latest
    if: always()
    permissions:
      contents: read

    steps:
      - name: Check test results
        run: |
          echo "## Bazel CI Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.test-minimal.result }}" == "success" ]; then
            echo "- ✅ Minimal configuration: Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "- ❌ Minimal configuration: Failed" >> $GITHUB_STEP_SUMMARY
          fi

          if [ "${{ needs.test-release-config.result }}" == "success" ]; then
            echo "- ✅ Release configuration: Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "- ❌ Release configuration: Failed" >> $GITHUB_STEP_SUMMARY
          fi

          if [ "${{ needs.test-debug-config.result }}" == "success" ]; then
            echo "- ✅ Debug configuration: Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "- ❌ Debug configuration: Failed" >> $GITHUB_STEP_SUMMARY
          fi

          # Fail if any required tests failed
          if [ "${{ needs.test-minimal.result }}" != "success" ] || \
             [ "${{ needs.test-release-config.result }}" != "success" ] || \
             [ "${{ needs.test-debug-config.result }}" != "success" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "❌ Some Bazel CI tests failed" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ All Bazel CI tests passed!" >> $GITHUB_STEP_SUMMARY
